server:
  port: 8084

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:postgresql://localhost:5432/seatguard_ticket
    username: ${DB_USERNAME:seatguard}
    password: ${DB_PASSWORD:seatguard_dev_2026}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ticket-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.LinkedHashMap

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

kafka:
  topics:
    booking-events: booking-events
