server:
  port: 8082

spring:
  application:
    name: event-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://localhost:5432/seatguard_event
    username: ${DB_USERNAME:seatguard}
    password: ${DB_PASSWORD:CHANGE_ME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 20

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:aVeryLongAndSecureSecretKeyForSeatGuardJWT2024PleaseChangeInProduction!56}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}
  secure: ${CLOUDINARY_SECURE:true}

logging:
  level:
    com.seatguard.event: INFO
    org.hibernate.SQL: WARN
