server:
  port: 8082

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/seatguard_event
    username: ${DB_USERNAME:seatguard}
    password: ${DB_PASSWORD:seatguard_dev_2026}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 20

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:aVeryLongAndSecureSecretKeyForSeatGuardJWT2024PleaseChangeInProduction!56}

logging:
  level:
    com.seatguard.event: INFO
    org.hibernate.SQL: WARN
